# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
    redis:
    # Redis数据库索引（默认为0）
      database: 0  
    # Redis服务器地址
      host: 127.0.0.1
    # Redis服务器连接端口
      port: 6379  
    # Redis服务器连接密码（默认为空）
      password:   
    # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 8  
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: 5000 
    # 连接池中的最大空闲连接
      pool.max-idle: 8  
    # 连接池中的最小空闲连接
      pool.min-idle: 0  
    # 连接超时时间（毫秒）
      timeout: 0

## Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
pagehelper:
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  auto-runtime-dialect: true

