# Tomcat
server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
#    port: 8443 #如果使用HTTPS，那需要监听在8443端口
#    ssl:
#      key-store: .keystore
#      key-store-password: 130119
#      key-store-type: JKS
#      key-alias: tomcat
      
# mysql
spring:
  # 环境 dev|test|pro
  profiles:
      active: dev
  output:
    ansi:
      enabled: detect #配置输出console的ide中的配色
  # jackson时间格式化
  jackson:
      time-zone: GMT+8
  #    default-property-inclusion: non_null    #忽略null字段
  #文件上传
  http:
    multipart: 
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #国际化        
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: false
  aop:
    auto: true
    # 使用JDK代理，只有这样才能用Spring AOP拦截Mapper接口实现类 
    proxy-target-class: false 