# Tomcat
server:
    port: 8088
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
#    port: 8443 #如果使用HTTPS，那需要监听在8443端口
#    ssl:
#      key-store: .keystore
#      key-store-password: 130119
#      key-store-type: JKS
#      key-alias: tomcat
      
# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    output:
      ansi:
        enabled: detect #配置输出console的ide中的配色
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
    #    default-property-inclusion: non_null    #忽略null字段
    #文件上传
    aop:
      auto: true
      proxy-target-class: true
    
## Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
    
# Mybatis PageHelper
pagehelper:
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  auto-runtime-dialect: true

