spring:
  redis:
  # Redis数据库索引（默认为0）
    database: 0  
  # Redis服务器连接密码（默认为空）
    password: 130119
  # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8  
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: 5000 
  # 连接池中的最大空闲连接
    pool.max-idle: 8  
  # 连接池中的最小空闲连接
    pool.min-idle: 0  
  # 连接超时时间（毫秒）
    timeout: 0
    cluster:
      nodes:
        - 192.168.1.102:6379
        - 192.168.1.103:6379
        - 192.168.1.107:6379
        - 192.168.1.108:6379
        - 192.168.1.109:6379
        - 192.168.1.110:6379